language: ruby

rvm:
  - 2.2

node_js:
  - "6"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

branches:
  only:
    - "master"

before_script:
  - npm install -g yarn
  - yarn

script:
  - npm run travis

notifications:
  email:
   - nathan.jessen@gmail.com

cache:
  yarn: true
  directories:
    - node_modules
