# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Custom vars
author:           "Nathan Jessen"
description:      ""
url:              "http://nathanjessen.github.io"
paginate:         10
linkedin:         "//www.linkedin.com/in/njessen/"
github:           "//github.com/nathanjessen"
email:            "nathan.jessen@gmail.com"