# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_site
exclude:          ["CNAME","README.md"]
port:             4000


# Custom vars
base_url:         "/"
author:           "Nathan Jessen"
description:      ""
url:              "http://semanticss.com"
paginate:         10
linkedin:         "//www.linkedin.com/in/njessen/"
github:           "//github.com/nathanjessen"
email:            "nathan.jessen@gmail.com"
