# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty
# permalink:        /:year/:title

# Server
# host:             0.0.0.0
port:             4502
destination:      /_site
exclude:          ["CNAME","README.md"]


# Custom vars
base_url:         "/"
author:           "Nathan Jessen"
description:      ""
url:              "http://semanticss.com"
paginate:         10
github:           "//github.com/nathanjessen"
linkedin:         "//www.linkedin.com/in/njessen/"
googleplus:       "//plus.google.com/108819920657113454025/posts"
email:            "nathan.jessen@gmail.com"
