# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Custom vars
author:           "Nathan Jessen"
description:      ""
url:              "http://nathanjessen.github.io"
paginate:         10
