####################
# Where things are
####################
# destination: ./_site
# plugins_dir: _plugins
# layouts_dir: _layouts
# data_dir: _data
# includes_dir: _includes
collections:
  posts:
    output: true
  projects:
    output: false


####################
# Handling Reading
####################
include:
  - "_pages"
exclude:
  - "node_modules"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "package.json"
  - "LICENSE.md"
  - "README.md"
  - "yarn.lock"


####################
# Filtering Content
####################
# show_drafts: null
# limit_posts: 0
# future: false
# unpublished: false


####################
# Plugins
####################
# whitelist: []
gems:
  - jekyll-sitemap


####################
# Conversion
####################
# markdown: kramdown
# excerpt_separator: "\n\n"


####################
# Serving
####################
# detach: false
# port: 4000
# host: 127.0.0.1
# baseurl: ""
# show_dir_listing: false


####################
# Outputting
####################
permalink: "categories/:categories/:title/"
# paginate_path: /page:num
timezone: "America/Los_Angeles"
# quiet: false
verbose: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: article
  -
    scope:
      path: "_pages"
      scope: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_slides"
    values:
      layout: "slides"
      permalink: "/slides/:slug/"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "page"
      permalink: "/projects/:path/"
# liquid:
#   error_mode: warn


####################
# Markdown Processors
####################
# rdiscount:
#   extensions: []
# redcarpet:
#   extensions: []
kramdown:
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # input: GFM
  # hard_wrap: false
  # footnote_nr: 1
  syntax_highlighter: rouge


####################
# Other
####################

# Liquid profiler - Generate a Liquid rendering profile to help you identify performance bottlenecks.
profile: false

# Custom vars
locale: "en-US"
title: "Nathan Jessen"
categories_path: categories.html
tags_path: tags.html
rss_path: atom.xml


####################
# Personal Information
####################

author: "Nathan Jessen"

# Contact
email: "nathan.jessen@gmail.com"
location: "Las Vegas, NV"

# Google Analytics
ga_domain: nathanjessen.github.io
ga_tracking_id: UA-42437510-1

# Social
githubs: "https://github.com/nathanjessen"
linkedin: "https://www.linkedin.com/in/njessen"
gplus: "//plus.google.com/+NathanJessen/posts"
twitter: "https://twitter.com/nathanjessen"
codepen: "http://codepen.io/njessen"
