title:            "Nathan Jessen"
author:           "Nathan Jessen"
BASE_PATH:        "http://nathanjessen.github.io"
# BASE_PATH:        "http://0.0.0.0:4000"
github_url:       "https://github.com/nathanjessen/nathanjessen.github.io"
description:      "Portfolio of Nathan Jessen"

# Server
# port:             4502
destination:      ./_site
include:          ["_pages"]
exclude:          ["vendor","CNAME","README.md","LICENSE.md","node_modules",".sass-cache","package.json","Gemfile","Gemfile.lock","gulpfile.js","*.sublime-project"]


permalink:        ":year/:month/:title/"


safe:             true
highlighter:      rouge
markdown:         "kramdown"
timezone:         "America/Chicago"


sass:
  style: expanded
  sass_dir: _scss

collections:
  projects:
    output: false
    # output: true
    # permalink: /projects/:path/



# Custom vars
base_url:         "/"
blog_url:         "/blog/"
rss_path:         atom.xml
categories_path:  categories.html
tags_path:        tags.html

# Google Analytics
ga_domain:        nathanjessen.github.io
ga_tracking_id:   UA-42437510-1


# Social
githubs:           "//github.com/nathanjessen"
linkedin:         "//www.linkedin.com/in/njessen/"
gplus:            "//plus.google.com/+NathanJessen/posts"
twitter:          "https://twitter.com/nathanjessen"
codepen:          "http://codepen.io/njessen"

# Contact
email:            "nathan.jessen@gmail.com"
location:         "Las Vegas, NV"
phone:            "(402) 427-3734"
tel:              "4024273734"

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
