title:            "Nathan Jessen"
author:           "Nathan Jessen"
BASE_PATH:        "http://nathanjessen.github.io"
# BASE_PATH:        "http://0.0.0.0:4000"
baseurl: ""
github_url:       "https://github.com/nathanjessen/nathanjessen.github.io"
description:      "Portfolio of Nathan Jessen"

# Server
# port:             4502
destination:      ./_site
include:          ["_pages"]
exclude:          ["vendor","CNAME","README.md","LICENSE.md","_data","_examples","node_modules","assets/.sass-cache"]


permalink:        ":year/:month/:title/"
relative_permalinks: false


safe:             true
pygments:         true
markdown:         "rdiscount"
timezone:         "America/Chicago"


# Custom vars
base_url:         "/"
blog_url:         "/blog/"
rss_path:         feed.xml
categories_path:  categories.html
tags_path:        tags.html

# Google Analytics
ga_domain:
ga_tracking_id:


# Social
githubs:           "//github.com/nathanjessen"
linkedin:         "//www.linkedin.com/in/njessen/"
gplus:            "//plus.google.com/108819920657113454025/posts"
email:            "nathan.jessen@gmail.com"
twitter:          "https://twitter.com/nathanjessen"
codepen:          "http://codepen.io/njessen"


# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
