# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

####################
# Where things are
####################
# destination: ./_site
# plugins_dir: _plugins
# layouts_dir: _layouts
# data_dir: _data
# includes_dir: _includes
collections:
  posts:
    output: true
  projects:
    output: false

####################
# Handling Reading
####################
include:
  - "_pages"
exclude:
  - "node_modules"
  - "vendor"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "package.json"
  - "LICENSE.md"
  - "README.md"
  - "yarn.lock"

####################
# Filtering Content
####################
# show_drafts: null
# limit_posts: 10
# future: false
# unpublished: false

####################
# Plugins
####################
# whitelist: []
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

####################
# Conversion
####################
# markdown: kramdown
# excerpt_separator: "\n\n"

####################
# Serving
####################
# detach: false
# port: 4000
# host: 127.0.0.1
# baseurl: ""
# show_dir_listing: false

####################
# Outputting
####################
permalink: ":categories/:title/"
# paginate_path: /page:num
timezone: "America/Los_Angeles"
verbose: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: article
  - scope:
      path: "_pages"
      scope: "pages"
    values:
      layout: "page"
  - scope:
      path: "slides"
    values:
      layout: "slides"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "page"

####################
# Markdown Processor
####################
kramdown:
  syntax_highlighter: rouge

####################
# Other
####################

# Liquid profiler - Generate a Liquid rendering profile to help you identify performance bottlenecks.
profile: false

# Custom vars
locale: "en-US"
title: "Nathan Jessen"
description: "Blog and Portfolio of Nathan Jessen"
categories_path: categories.html
tags_path: tags.html
rss_path: atom.xml

####################
# Personal Information
####################

author: "Nathan Jessen"
# logo:

# Contact
email: "nathan.jessen@gmail.com"
location: "Las Vegas, NV"

# Google Analytics
ga_domain: nathanjessen.github.io
ga_tracking_id: UA-42437510-1

# Social
githubs:
  username: "nathanjessen"
# codepen:
#   username: "njessen"
# twitter:
#   username:
# medium:
#   username: "@nathanjessen"
linkedin:
  username: "njessen"
# gplus:
#   username:
# instagram:
#   username:
# dribbble:
#   username:
# angellist:
#   username:

# jekyll-seo-tag - social profiles
social:
  links:
    - https://github.com/nathanjessen"
    - http://codepen.io/njessen"
    - https://medium.com/@nathanjessen"
    - https://www.linkedin.com/in/njessen"
